server:
  port: 9300

eureka:
  client:
    service-url:
      host: ${EUREKA_HOST:localhost}
      port: ${EUREKA_PORT:8761}
      defaultZone: http://${eureka.client.service-url.host}:${eureka.client.service-url.port}/eureka/

management:
  server:
    port: 9301
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: integration-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/balance-groups/**
        - id: balance-calculator-service
          uri: lb://BALANCE-CALCULATOR-SERVICE
          predicates:
            - Path=/api/balance-group/**

logging:
  file:
    path: ./logs
    name: ${spring.application.name}
